
name: Hello World Workflow

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
