
name: crontime
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # Manual trigger from Actions tab
  push:
    paths:
      - ".github/workflows/withcron.yml"  # optional: runs on future edits to the file

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
